- platform: mqtt
  name: "Fingerprint"
  state_topic: "/fingerprint/mode/status"
  value_template: "{{value_json.state}}"
  json_attributes_topic: "/fingerprint/mode/status"
  json_attributes_template: "{{value_json | tojson}}"
- platform: template
  sensors:
    fingerprint_mode:
      friendly_name: "Fingerprint Sensor Mode"
      value_template: >-
        {{state_attr('sensor.fingerprint', 'mode')}}
      icon_template: >-
        {% if is_state('sensor.fingerprint_mode', 'reading') %}
          mdi:focus-field
        {% elif is_state('sensor.fingerprint_mode', 'learning') %}
          mdi:draw
        {% elif is_state('sensor.fingerprint_mode', 'deleting') %}
          mdi:trash-can-outline
        {% endif %}
    fingerprint_state:
      friendly_name: "Fingerprint State"
      value_template: >-
        {{states('sensor.fingerprint')}}
      icon_template: >-
        {% if is_state('sensor.fingerprint', 'Waiting') %}
          mdi:fingerprint
        {% elif is_state('sensor.fingerprint', 'Matched') %}
          mdi:shield-check
        {% elif is_state('sensor.fingerprint', 'Not matched') %}
          mdi:fingerprint-off
        {% endif %}
    fingerprint_id:
      friendly_name: "Fingerprint ID"
      value_template: >-
        {{state_attr('sensor.fingerprint', 'id')}}
    fingerprint_person:
      friendly_name: "Fingerprint Person"
      value_template: >-
        {% if states.sensor.fingerprint_id.state | int > 0.1 %}
          {{state_attr('saver.saver', 'variables')[states('sensor.fingerprint_id')] }}
        {% elif is_state('sensor.fingerprint', 'Waiting') %}
          
        {% elif is_state('sensor.fingerprint', 'Not matched') %}
          Not matched
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.fingerprint', 'Waiting') %}
          mdi:human-male
        {% elif is_state('sensor.fingerprint', 'Matched') %}
          mdi:human-greeting
        {% elif is_state('sensor.fingerprint', 'Not matched') %}
          mdi:police-badge
        {% elif is_state('sensor.fingerprint', 'Deleted') %}
          mdi:trash-can-outline
        {% endif %}